---
language: java
sudo: false
script: mvn clean verify

deploy:
   provider: cloudfoundry
   username: richar.fernandezv@gmail.com
   password: ric.fevil.Pivotal.123
   deployment: banking-qa
   api: https://api.run.pivotal.io
   organization: rfernandezv
   space: qa